server: 
    port: 7080
    error: 
        whitelabel: 
            enabled: true
    servlet: 
        jsp: 
            init-parameters: 
                development: true

spring:
    db1: 
        datasource:
            hikari: 
                driver-class-name: oracle.jdbc.driver.OracleDriver
                jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
                username: system
                password: db2admin
    db2: 
        datasource: 
            hikari: 
                driver-class-name: oracle.jdbc.driver.OracleDriver
                jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
                username: system
                password: db2admin
    mvc: 
        view: 
            prefix: /WEB-INF/views/
            suffix: .jsp
#    thymeleaf:
#        cache: false
