server: 
    port: 7081
    connection-timeout: 10s
    tomcat: 
        accept-count: 100
        max-connections: 10000
        max-threads: 200
        min-spare-threads: 10
        max-swallow-size: 2MB
    error: 
        whitelabel: 
            enabled: true
    servlet: 
        jsp: 
            init-parameters: 
                development: true
    ssl: 
        enabled: true
        protocol: TLS
        enabled-protocols: 
        - TLSv1
        - TLSv1.1
        - TLSv1.2
        key-store: D:/AppHome/framework/dstone-boot/ssl/dstone-keystore.p12
        key-store-type: PKCS12
        key-store-password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
        key-store-alias: dstone-ssl

spring:
    main:
        allow-bean-definition-overriding: true
    datasource: 
        common:
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sampleDB
                username: ENC(ydLjxrknr8dD59e6E+HvxdxRaGiFa9jOCpJJDtb0uak=)
                password: ENC(ydLjxrknr8dD59e6E+HvxdxRaGiFa9jOCpJJDtb0uak=)
                maximum-pool-size: 50
                use-jndi-lookup: N
                jndi-lookup-name: java:comp/env/sampleDB
            networks: 
                - backend                
        sample:
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sampleDB
                username: ENC(RxKuJmDmzNwlIYKQOUjUlAC4mm4RPraeCDJWbUh99w0=)
                password: ENC(RxKuJmDmzNwlIYKQOUjUlAC4mm4RPraeCDJWbUh99w0=)
                maximum-pool-size: 50
                use-jndi-lookup: N
                jndi-lookup-name: java:comp/env/sampleDB
            networks: 
                - backend
        sample-oracle: 
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
                username: ENC(1Vc8JCXoCl4GBsif5/DgOWd/UaRQGzbDPxdCBTcotwU=)
                password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
                maximum-pool-size: 50
                use-jndi-lookup: N
                jndi-lookup-name: java:comp/env/xe
            networks: 
                - backend
        analyzer:
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/analyze
                username: ENC(tbOV8vzCOtfGOBgpBX/We1kvA0ueyPydKMOYGOaarCI=)
                password: ENC(tbOV8vzCOtfGOBgpBX/We1kvA0ueyPydKMOYGOaarCI=)
                maximum-pool-size: 50
                use-jndi-lookup: N
                jndi-lookup-name: java:comp/env/analyze
            networks: 
                - backend
    rabbitmq: 
        host: localhost
        port: 5672
        username: jysn007
        password: db2admin

resources: 
    fileUp: 
        path: D:/Temp

interface: 
    kakao: 
      # 발급받은 클라이언트ID
      client-id: 6f89f3f82713133646791acf04bb78c7
      # 1. 로그인 URL
      login-url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=@client_id@&redirect_uri=@redirect_uri@
      # 2. 로그인 후 콜백 URL
      login-redirect-uri: https://localhost:7081/kakao/loginCallback.do
      # 3. 사용자토큰 조회 URL
      access-token-url: https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id=@client_id@&redirect_uri=@redirect_uri@&code=@code@
      # 4. 사용자정보 조회 URL
      userinfo-url: https://kapi.kakao.com/v2/user/me
      # 5. 로그아웃 URL
      logout-url: https://kauth.kakao.com/oauth/logout?response_type=code&client_id=@client_id@&logout_redirect_uri=@logout_redirect_uri@
      # 6. 로그아웃 후 콜백 URL
      logout-redirect-uri: https://localhost:7081/kakao/logoutCallback.do