server: 
    port: 7080
    connection-timeout: 10s
    tomcat: 
        accept-count: 100
        max-connections: 10000
        max-threads: 200
        min-spare-threads: 10
        max-swallow-size: 2MB
    error: 
        whitelabel: 
            enabled: true
    servlet: 
        jsp: 
            init-parameters: 
                development: true
    ssl: 
        enabled: true
        protocol: TLS
        enabled-protocols: 
        - TLSv1
        - TLSv1.1
        - TLSv1.2
        key-store: D:/AppHome/dstone-boot/ssl/dstone-keystore.p12
        key-store-type: PKCS12
        key-store-password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
        key-store-alias: dstone-ssl

spring:
    datasource: 
        db1:
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
                username: ENC(1Vc8JCXoCl4GBsif5/DgOWd/UaRQGzbDPxdCBTcotwU=)
                password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
            networks: 
                - backend
        db2: 
            hikari: 
                driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
                jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
                username: ENC(1Vc8JCXoCl4GBsif5/DgOWd/UaRQGzbDPxdCBTcotwU=)
                password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
            networks: 
                - backend
    rabbitmq: 
        host: localhost
        port: 5672
        username: jysn007
        password: db2admin
                
    mvc: 
        view: 
            prefix: /WEB-INF/views/
            suffix: .jsp
#    thymeleaf:
#        cache: false


