server: 
    port: 9080
    error: 
        whitelabel: 
            enabled: true
    servlet: 
        jsp: 
            init-parameters: 
                development: true

spring:
    db1: 
        datasource:
            hikari: 
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://localhost:3306/memberDB?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: root
                password: db2admin
    db2: 
        datasource: 
            hikari: 
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://localhost:3306/deptDB?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
                username: root
                password: db2admin
    mvc: 
        view: 
            prefix: /WEB-INF/views/
            suffix: .jsp
#    thymeleaf:
#        cache: false
