
/**********************************************
Dataflow 데이터베이스[배치관리서버용] 테이블
**********************************************/

-- ============================================
-- Spring Batch 5.1.0 Schema for MySQL 5.7
-- ============================================
USE dataflow;

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6) DEFAULT NULL,
    END_TIME DATETIME(6) DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6) DEFAULT NULL,
    END_TIME DATETIME(6) DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM BATCH_STEP_EXECUTION_SEQ);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM BATCH_JOB_EXECUTION_SEQ);

CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM BATCH_JOB_SEQ);

-- ============================================
-- Spring Cloud Task 3.1.1 Schema for MySQL 5.7
-- ============================================

CREATE TABLE IF NOT EXISTS TASK_EXECUTION (
    TASK_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    START_TIME DATETIME DEFAULT NULL,
    END_TIME DATETIME DEFAULT NULL,
    TASK_NAME VARCHAR(100),
    EXIT_CODE INTEGER,
    EXIT_MESSAGE VARCHAR(2500),
    ERROR_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    EXTERNAL_EXECUTION_ID VARCHAR(255),
    PARENT_EXECUTION_ID BIGINT
) ;

CREATE TABLE IF NOT EXISTS TASK_EXECUTION_PARAMS (
    TASK_EXECUTION_ID BIGINT NOT NULL,
    TASK_PARAM VARCHAR(2500),
    CONSTRAINT TASK_EXEC_PARAMS_FK FOREIGN KEY (TASK_EXECUTION_ID)
        REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS TASK_TASK_BATCH (
    TASK_EXECUTION_ID BIGINT NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CONSTRAINT TASK_EXEC_BATCH_FK FOREIGN KEY (TASK_EXECUTION_ID)
        REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS TASK_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO TASK_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM TASK_SEQ);

CREATE TABLE IF NOT EXISTS TASK_LOCK (
    LOCK_KEY CHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CLIENT_ID CHAR(36),
    CREATED_DATE DATETIME(6) NOT NULL,
    CONSTRAINT LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
) ;



CREATE OR REPLACE VIEW `AGGREGATE_JOB_EXECUTION` AS 
SELECT
  `BATCH_JOB_EXECUTION`.`JOB_EXECUTION_ID` AS `JOB_EXECUTION_ID`,
  `BATCH_JOB_EXECUTION`.`VERSION`          AS `VERSION`,
  `BATCH_JOB_EXECUTION`.`JOB_INSTANCE_ID`  AS `JOB_INSTANCE_ID`,
  `BATCH_JOB_EXECUTION`.`CREATE_TIME`      AS `CREATE_TIME`,
  `BATCH_JOB_EXECUTION`.`START_TIME`       AS `START_TIME`,
  `BATCH_JOB_EXECUTION`.`END_TIME`         AS `END_TIME`,
  `BATCH_JOB_EXECUTION`.`STATUS`           AS `STATUS`,
  `BATCH_JOB_EXECUTION`.`EXIT_CODE`        AS `EXIT_CODE`,
  `BATCH_JOB_EXECUTION`.`EXIT_MESSAGE`     AS `EXIT_MESSAGE`,
  `BATCH_JOB_EXECUTION`.`LAST_UPDATED`     AS `LAST_UPDATED`,
  'boot2'                                  AS `SCHEMA_TARGET`
FROM `BATCH_JOB_EXECUTION`
;

CREATE OR REPLACE VIEW `AGGREGATE_JOB_INSTANCE` AS 
SELECT
  `BATCH_JOB_INSTANCE`.`JOB_INSTANCE_ID` AS `JOB_INSTANCE_ID`,
  `BATCH_JOB_INSTANCE`.`VERSION`         AS `VERSION`,
  `BATCH_JOB_INSTANCE`.`JOB_NAME`        AS `JOB_NAME`,
  `BATCH_JOB_INSTANCE`.`JOB_KEY`         AS `JOB_KEY`,
  'boot2'                                AS `SCHEMA_TARGET`
FROM `BATCH_JOB_INSTANCE`
;


CREATE OR REPLACE VIEW `AGGREGATE_STEP_EXECUTION` AS 
SELECT
  `BATCH_STEP_EXECUTION`.`STEP_EXECUTION_ID`  AS `STEP_EXECUTION_ID`,
  `BATCH_STEP_EXECUTION`.`VERSION`            AS `VERSION`,
  `BATCH_STEP_EXECUTION`.`STEP_NAME`          AS `STEP_NAME`,
  `BATCH_STEP_EXECUTION`.`JOB_EXECUTION_ID`   AS `JOB_EXECUTION_ID`,
  `BATCH_STEP_EXECUTION`.`START_TIME`         AS `START_TIME`,
  `BATCH_STEP_EXECUTION`.`END_TIME`           AS `END_TIME`,
  `BATCH_STEP_EXECUTION`.`STATUS`             AS `STATUS`,
  `BATCH_STEP_EXECUTION`.`COMMIT_COUNT`       AS `COMMIT_COUNT`,
  `BATCH_STEP_EXECUTION`.`READ_COUNT`         AS `READ_COUNT`,
  `BATCH_STEP_EXECUTION`.`FILTER_COUNT`       AS `FILTER_COUNT`,
  `BATCH_STEP_EXECUTION`.`WRITE_COUNT`        AS `WRITE_COUNT`,
  `BATCH_STEP_EXECUTION`.`READ_SKIP_COUNT`    AS `READ_SKIP_COUNT`,
  `BATCH_STEP_EXECUTION`.`WRITE_SKIP_COUNT`   AS `WRITE_SKIP_COUNT`,
  `BATCH_STEP_EXECUTION`.`PROCESS_SKIP_COUNT` AS `PROCESS_SKIP_COUNT`,
  `BATCH_STEP_EXECUTION`.`ROLLBACK_COUNT`     AS `ROLLBACK_COUNT`,
  `BATCH_STEP_EXECUTION`.`EXIT_CODE`          AS `EXIT_CODE`,
  `BATCH_STEP_EXECUTION`.`EXIT_MESSAGE`       AS `EXIT_MESSAGE`,
  `BATCH_STEP_EXECUTION`.`LAST_UPDATED`       AS `LAST_UPDATED`,
  'boot2'                                     AS `SCHEMA_TARGET`
FROM `BATCH_STEP_EXECUTION`
;

CREATE OR REPLACE VIEW `AGGREGATE_TASK_BATCH` AS 
SELECT
  `TASK_TASK_BATCH`.`TASK_EXECUTION_ID` AS `TASK_EXECUTION_ID`,
  `TASK_TASK_BATCH`.`JOB_EXECUTION_ID`  AS `JOB_EXECUTION_ID`,
  'boot2'                               AS `SCHEMA_TARGET`
FROM `TASK_TASK_BATCH`
;

CREATE OR REPLACE VIEW `AGGREGATE_TASK_EXECUTION` AS 
SELECT
  `TASK_EXECUTION`.`TASK_EXECUTION_ID`     AS `TASK_EXECUTION_ID`,
  `TASK_EXECUTION`.`START_TIME`            AS `START_TIME`,
  `TASK_EXECUTION`.`END_TIME`              AS `END_TIME`,
  `TASK_EXECUTION`.`TASK_NAME`             AS `TASK_NAME`,
  `TASK_EXECUTION`.`EXIT_CODE`             AS `EXIT_CODE`,
  `TASK_EXECUTION`.`EXIT_MESSAGE`          AS `EXIT_MESSAGE`,
  `TASK_EXECUTION`.`ERROR_MESSAGE`         AS `ERROR_MESSAGE`,
  `TASK_EXECUTION`.`LAST_UPDATED`          AS `LAST_UPDATED`,
  `TASK_EXECUTION`.`EXTERNAL_EXECUTION_ID` AS `EXTERNAL_EXECUTION_ID`,
  `TASK_EXECUTION`.`PARENT_EXECUTION_ID`   AS `PARENT_EXECUTION_ID`,
  'boot2'                                  AS `SCHEMA_TARGET`
FROM `TASK_EXECUTION`
;

CREATE OR REPLACE VIEW `AGGREGATE_TASK_EXECUTION_PARAMS` AS 
SELECT
  `TASK_EXECUTION_PARAMS`.`TASK_EXECUTION_ID` AS `TASK_EXECUTION_ID`,
  `TASK_EXECUTION_PARAMS`.`TASK_PARAM`        AS `TASK_PARAM`,
  'boot2'                                     AS `SCHEMA_TARGET`
FROM `TASK_EXECUTION_PARAMS`
;

-- ============================================
-- Spring Cloud Data Flow 2.11.5 Schema for MySQL 5.7
-- ============================================

CREATE TABLE IF NOT EXISTS HIBERNATE_SEQUENCE (
    NEXT_VAL BIGINT
) ;

INSERT INTO HIBERNATE_SEQUENCE VALUES (1);

CREATE TABLE IF NOT EXISTS APP_REGISTRATION (
    ID BIGINT NOT NULL PRIMARY KEY,
    OBJECT_VERSION BIGINT,
    DEFAULT_VERSION BIT(1),
    METADATA_URI TEXT,
    NAME VARCHAR(255),
    TYPE INT,
    URI TEXT,
    VERSION VARCHAR(255),
    BOOT_VERSION VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS AUDIT_RECORDS (
    ID BIGINT NOT NULL PRIMARY KEY,
    AUDIT_ACTION BIGINT,
    AUDIT_DATA LONGTEXT,
    AUDIT_OPERATION BIGINT,
    CORRELATION_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_ON DATETIME,
    PLATFORM_NAME VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS STREAM_DEFINITIONS (
    DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    DEFINITION TEXT,
    DESCRIPTION VARCHAR(255),
    ORIGINAL_DEFINITION TEXT
) ;

CREATE TABLE IF NOT EXISTS TASK_DEFINITIONS (
    DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    DEFINITION TEXT,
    DESCRIPTION VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS TASK_DEPLOYMENT (
    ID BIGINT NOT NULL PRIMARY KEY,
    OBJECT_VERSION BIGINT,
    TASK_DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    TASK_DEFINITION_NAME VARCHAR(255) NOT NULL,
    PLATFORM_NAME VARCHAR(255) NOT NULL,
    CREATED_ON DATETIME,
    CONSTRAINT TASK_DEPLOYMENT_UK UNIQUE (TASK_DEPLOYMENT_ID)
) ;

CREATE TABLE IF NOT EXISTS TASK_EXECUTION_METADATA (
    ID BIGINT NOT NULL PRIMARY KEY,
    TASK_EXECUTION_ID BIGINT NOT NULL,
    TASK_EXECUTION_MANIFEST TEXT,
    CONSTRAINT TASK_METADATA_FK FOREIGN KEY (TASK_EXECUTION_ID)
        REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID) ON DELETE CASCADE
) ;

CREATE TABLE IF NOT EXISTS TASK_EXECUTION_METADATA_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO TASK_EXECUTION_METADATA_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM TASK_EXECUTION_METADATA_SEQ);

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
    VERSION_RANK INT NOT NULL,
    INSTALLED_RANK INT NOT NULL,
    VERSION VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(200) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    SCRIPT VARCHAR(1000) NOT NULL,
    CHECKSUM INT,
    INSTALLED_BY VARCHAR(100) NOT NULL,
    INSTALLED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXECUTION_TIME INT NOT NULL,
    SUCCESS BIT(1) NOT NULL,
    INDEX SCHEMA_VERSION_IR_IDX (INSTALLED_RANK),
    INDEX SCHEMA_VERSION_S_IDX (SUCCESS)
) ;

