
USE sampleDB;

CREATE TABLE IF NOT EXISTS SAMPLE_MEMBER (
  GROUP_ID VARCHAR(30) NOT NULL, 
  USER_ID VARCHAR(30) NOT NULL, 
  USER_PW VARCHAR(30) ,   
  MEMBER_NAME VARCHAR(40) NOT NULL,   
  AGE VARCHAR(12) ,   
  DUTY VARCHAR(40) ,     
  REGION VARCHAR(100) , 
  ADDRESS VARCHAR(255) , 
  ADDRESS_DTL VARCHAR(255) ,  
  JUMINNO VARCHAR(13) ,    
  GENDER VARCHAR(2) ,    
  TEL VARCHAR(15) ,    
  HP VARCHAR(15) ,    
  EMAIL VARCHAR(150) ,   
  INPUT_DT DATE NOT NULL,  
  UPDATE_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID, USER_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP (
  GROUP_ID VARCHAR(30) NOT NULL, 
  GROUP_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE (
  ROLE_ID VARCHAR(30) NOT NULL, 
  ROLE_NAME VARCHAR(40) NOT NULL,    
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_GROUP_ROLE (
  GROUP_ID VARCHAR(30) NOT NULL, 
  ROLE_ID VARCHAR(30) NOT NULL, 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (GROUP_ID, ROLE_ID)
) ;

CREATE TABLE IF NOT EXISTS SAMPLE_ROLE_PROG (
  ROLE_ID VARCHAR(30) NOT NULL, 
  PROG_ID VARCHAR(30) NOT NULL, 
  PROG_NAME VARCHAR(200), 
  PROG_URL VARCHAR(200), 
  INPUT_DT DATE NOT NULL,  
  PRIMARY KEY  (ROLE_ID, PROG_ID)
) ;


USE analyzeDB;

CREATE TABLE TB_SYS ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  SYS_NM VARCHAR(200) COMMENT '시스템명', 
  CONF_FILE_PATH VARCHAR(500) NOT NULL COMMENT '설정파일경로', 
  APP_ROOT_PATH VARCHAR(500) NOT NULL COMMENT '어플리케이션루트', 
  APP_SRC_PATH VARCHAR(4000) NOT NULL COMMENT '어플리케이션서버소스루트', 
  APP_WEB_PATH VARCHAR(4000) NOT NULL COMMENT '어플리케이션웹소스루트', 
  APP_SQL_PATH VARCHAR(4000) NOT NULL COMMENT '어플리케이션쿼리소스루트', 
  WRITE_PATH VARCHAR(500) COMMENT '분석결과생성경로', 
  SAVE_FILE_NAME VARCHAR(500) COMMENT '분석결과저장파일명', 
  DBID VARCHAR(10) COMMENT 'DBID', 
  IS_TABLE_LIST_FROM_DB VARCHAR(10) COMMENT '테이블목록을DB로부터읽어올지여부', 
  TABLE_NAME_LIKE_STR VARCHAR(500) COMMENT '테이블명을DB로부터읽어올때적용할프리픽스', 
  TABLE_LIST_FILE_NAME VARCHAR(500) COMMENT '테이블목록정보파일명', 
  IS_SAVE_TO_DB VARCHAR(10) COMMENT '작업결과를DB에저장할지여부', 
  APP_JDK_HOME VARCHAR(200) COMMENT '분석대상어플리케이션JDK홈', 
  APP_CLASSPATH TEXT COMMENT '분석대상어플리케이션클래스패스', 
  WORKER_THREAD_KIND VARCHAR(2) COMMENT '분석작업을진행할쓰레드핸들러종류', 
  WORKER_THREAD_NUM VARCHAR(10) COMMENT '분석작업을진행할쓰레드갯수', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID) 
) COMMENT '시스템'; 
CREATE TABLE TB_CLZZ ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  CLZZ_ID VARCHAR(300) NOT NULL COMMENT '클래스ID', 
  PKG_ID VARCHAR(200) COMMENT '패키지', 
  CLZZ_NM VARCHAR(200) COMMENT '클래스명', 
  CLZZ_KIND VARCHAR(2) COMMENT '기능종류(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  RESOURCE_ID VARCHAR(100) COMMENT '리소스ID', 
  CLZZ_INTF VARCHAR(1) COMMENT '클래스or인터페이스', 
  INTF_ID_LIST TEXT COMMENT '상위인터페이스ID목록', 
  PARENT_CLZZ_ID VARCHAR(300) COMMENT '상위클래스ID', 
  INTF_IMPL_CLZZ_ID_LIST TEXT COMMENT '인터페이스구현하위클래스ID목록', 
  MEMBER_ALIAS_LIST TEXT COMMENT '호출알리아스', 
  FILE_NAME VARCHAR(1000) COMMENT '파일명', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, CLZZ_ID) 
) COMMENT '클래스'; 
CREATE TABLE TB_FUNC ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  FUNC_ID VARCHAR(300) NOT NULL COMMENT '기능ID', 
  CLZZ_ID VARCHAR(300) NOT NULL COMMENT '클래스ID', 
  MTD_ID VARCHAR(300) COMMENT '메서드ID', 
  MTD_NM VARCHAR(400) COMMENT '메서드명', 
  MTD_URL VARCHAR(300) COMMENT '메서드URL', 
  FILE_NAME VARCHAR(1000) COMMENT '파일명', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, FUNC_ID) 
) COMMENT '기능메서드'; 
CREATE TABLE TB_TBL ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  TBL_ID VARCHAR(100) NOT NULL COMMENT '테이블ID', 
  TBL_OWNER VARCHAR(100) COMMENT '테이블오너', 
  TBL_NM VARCHAR(200) COMMENT '테이블명', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, TBL_ID) 
) COMMENT '테이블'; 
CREATE TABLE TB_FUNC_FUNC_MAPPING ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  FUNC_ID VARCHAR(300) NOT NULL COMMENT '기능ID', 
  CALL_FUNC_ID VARCHAR(300) NOT NULL COMMENT '호출기능ID', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, FUNC_ID, CALL_FUNC_ID) 
) COMMENT '기능간맵핑'; 
CREATE TABLE TB_FUNC_TBL_MAPPING ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  FUNC_ID VARCHAR(300) NOT NULL COMMENT '기능ID', 
  TBL_ID VARCHAR(100) NOT NULL COMMENT '테이블ID', 
  JOB_KIND VARCHAR(10) COMMENT '작업종류', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, FUNC_ID, TBL_ID, JOB_KIND) 
) COMMENT '테이블맵핑'; 
CREATE TABLE TB_UI ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  UI_ID VARCHAR(100) NOT NULL COMMENT '화면ID', 
  UI_NM VARCHAR(200) COMMENT '화면명', 
  FILE_NAME VARCHAR(1000) COMMENT '파일명', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, UI_ID) 
) COMMENT '화면'; 
CREATE TABLE TB_UI_FUNC_MAPPING ( 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  UI_ID VARCHAR(100) NOT NULL COMMENT '화면ID', 
  MTD_URL VARCHAR(300) NOT NULL COMMENT '메서드URL', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, UI_ID, MTD_URL) 
) COMMENT '화면기능맵핑'; 
CREATE TABLE TB_METRIX ( 
  SEQ BIGINT UNSIGNED NOT NULL COMMENT '시퀀스', 
  SYS_ID VARCHAR(20) NOT NULL COMMENT '시스템ID', 
  UI_ID VARCHAR(100) COMMENT '화면ID', 
  UI_NM VARCHAR(200) COMMENT '화면명', 
  BASIC_URL VARCHAR(300) COMMENT '기준URL', 
  FUNCTION_ID_1 VARCHAR(300) COMMENT '기능ID_1', 
  FUNCTION_NAME_1 VARCHAR(400) COMMENT '기능명_1', 
  CLASS_KIND_1 VARCHAR(2) COMMENT '클래스종류1(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_2 VARCHAR(300) COMMENT '기능ID_2', 
  FUNCTION_NAME_2 VARCHAR(400) COMMENT '기능명_2', 
  CLASS_KIND_2 VARCHAR(2) COMMENT '클래스종류2(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_3 VARCHAR(300) COMMENT '기능ID_3', 
  FUNCTION_NAME_3 VARCHAR(400) COMMENT '기능명_3', 
  CLASS_KIND_3 VARCHAR(2) COMMENT '클래스종류3(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_4 VARCHAR(300) COMMENT '기능ID_4', 
  FUNCTION_NAME_4 VARCHAR(400) COMMENT '기능명_4', 
  CLASS_KIND_4 VARCHAR(2) COMMENT '클래스종류4(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_5 VARCHAR(300) COMMENT '기능ID_5', 
  FUNCTION_NAME_5 VARCHAR(400) COMMENT '기능명_5', 
  CLASS_KIND_5 VARCHAR(2) COMMENT '클래스종류5(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_6 VARCHAR(300) COMMENT '기능ID_6', 
  FUNCTION_NAME_6 VARCHAR(400) COMMENT '기능명_6', 
  CLASS_KIND_6 VARCHAR(2) COMMENT '클래스종류6(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_7 VARCHAR(300) COMMENT '기능ID_7', 
  FUNCTION_NAME_7 VARCHAR(400) COMMENT '기능명_7', 
  CLASS_KIND_7 VARCHAR(2) COMMENT '클래스종류7(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_8 VARCHAR(300) COMMENT '기능ID_8', 
  FUNCTION_NAME_8 VARCHAR(400) COMMENT '기능명_8', 
  CLASS_KIND_8 VARCHAR(2) COMMENT '클래스종류8(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_9 VARCHAR(300) COMMENT '기능ID_9', 
  FUNCTION_NAME_9 VARCHAR(400) COMMENT '기능명_9', 
  CLASS_KIND_9 VARCHAR(2) COMMENT '클래스종류9(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  FUNCTION_ID_10 VARCHAR(300) COMMENT '기능ID_10', 
  FUNCTION_NAME_10 VARCHAR(400) COMMENT '기능명_10', 
  CLASS_KIND_10 VARCHAR(2) COMMENT '클래스종류10(CT:컨트롤러/SV:서비스/DA:DAO/OT:나머지)', 
  CALL_TBL VARCHAR(4000) COMMENT '호출테이블', 
  WORKER_ID VARCHAR(10) NOT NULL COMMENT '입력자ID', 
  PRIMARY KEY (SYS_ID, SEQ) 
) COMMENT '종합메트릭스'; 


